---
defaultGroups:
    - adm
    - cdrom
    - dip
    - plugdev
    - sudo
    - name: lpadmin
      must_exist: false
      system: true
    - name: sambashare
      must_exist: false
      system: true
doAutologin: false
setRootPassword: false
sudoersGroup: sudo
passwordRequirements:
    minLength: 1
    maxLength: -1
allowWeakPasswords: true
allowWeakPasswordsDefault: false
user:
    shell: /bin/bash
    forbidden_names: [ root ]
hostname:
    location: EtcFile
    writeHostsFile: true
