# Jungey OS installer: which pages are shown and what runs, in order.
---
modules-search: [ local ]

instances:
- id:       touch_initrd
  module:   shellprocess
  config:   shellprocess_touch_initrd.conf
- id:       jungey_finish
  module:   shellprocess
  config:   shellprocess_jungey_finish.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - shellprocess@touch_initrd
  - initramfscfg
  - initramfs
  - grubcfg
  - bootloader
  - packages
  - shellprocess@jungey_finish
  - umount
- show:
  - finished

branding: jungey
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
