[greeter]
background=/usr/share/backgrounds/jungey/jungey-default.png
theme-name=Greybird-dark
icon-theme-name=elementary-xfce-dark
cursor-theme-name=DMZ-White
font-name=Ubuntu 11
default-user-image=#avatar-default
indicators=~host;~spacer;~clock;~spacer;~session;~a11y;~power
clock-format=%a %d %b, %H:%M
position=35%,center 50%,center
