[greeter]
background=/usr/share/backgrounds/jungey/jungey-login.png
theme-name=Jungey
icon-theme-name=Papirus-Dark
cursor-theme-name=DMZ-White
font-name=Inter 11
default-user-image=#avatar-default
indicators=~host;~spacer;~clock;~spacer;~session;~a11y;~power
clock-format=%a %d %b, %H:%M
position=35%,center 50%,center
